import {MigrationInterface, QueryRunner} from "typeorm";

export class InitialSetup1693286470194 implements MigrationInterface {
    name = 'InitialSetup1693286470194'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "project_address" ("id" SERIAL NOT NULL, "addressLine1" character varying(255), "addressLine2" character varying(255), "city" character varying(255), "stateOrProvince" character varying(255), "zipOrPostalCode" character varying(255), "country" character varying(255), "projectId" integer, CONSTRAINT "REL_e0d07dea550d59fab79f008fc5" UNIQUE ("projectId"), CONSTRAINT "PK_671bb902fafec9019c5ceebd6ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."project_location_type_enum" AS ENUM('site', 'building', 'storey', 'space')`);
        await queryRunner.query(`CREATE TABLE "project_location" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "type" "public"."project_location_type_enum" NOT NULL DEFAULT 'site', "address" character varying(255), "coordinate" character varying(255), "createdBy" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "projectId" integer, "parentLocationId" integer, CONSTRAINT "PK_e0573085d178a5a31e5a1914802" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "login" character varying(255) NOT NULL, "password" character varying(512) NOT NULL, "name" character varying(255) NOT NULL, "firstName" character varying(255) NOT NULL, "email" character varying(255), "active" boolean NOT NULL DEFAULT true, "blocked" boolean NOT NULL DEFAULT false, "blockingReason" character varying(512), "salt" character varying(512) NOT NULL, "parallelLogins" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "unique-user-login" ON "user" ("login") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "unique-user-salt" ON "user" ("salt") `);
        await queryRunner.query(`CREATE TYPE "public"."project_participant_role_enum" AS ENUM('Guest', 'Contributor')`);
        await queryRunner.query(`CREATE TABLE "project_participant" ("id" SERIAL NOT NULL, "role" "public"."project_participant_role_enum" DEFAULT 'Guest', "userId" integer, "projectId" integer, CONSTRAINT "unique-user-project" UNIQUE ("userId", "projectId"), CONSTRAINT "PK_149de99a476203f813c3cb43a09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."project_projecttype_enum" AS ENUM('deconstruction', 'renovation')`);
        await queryRunner.query(`CREATE TABLE "project" ("id" SERIAL NOT NULL, "projectType" "public"."project_projecttype_enum" DEFAULT 'deconstruction', "shortName" character varying(255) NOT NULL, "fullName" character varying(255) NOT NULL, "description" character varying(1024), "deconstructionStart" TIMESTAMP, "footprint" integer, "contactInfo" character varying(255), "createdBy" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "ownerId" integer, CONSTRAINT "PK_4d68b1358bb5b766d3e78f32f57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "unique-project-shortName" ON "project" ("shortName") `);
        await queryRunner.query(`CREATE TABLE "material_type" ("uid" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "category" character varying NOT NULL, "isHazard" boolean DEFAULT false, "projectId" integer, CONSTRAINT "unique_materialtype_name_project" UNIQUE ("name", "projectId"), CONSTRAINT "PK_85d7945dd49f99bb930c0203d2d" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "material" ("uid" uuid NOT NULL DEFAULT uuid_generate_v4(), "volume" numeric, "mass" numeric, "projectId" integer, "materialTypeUid" uuid, "elementUid" uuid, CONSTRAINT "PK_97dcf28cf48060a8e1b96f353f1" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "point_of_interest" ("uid" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "poiId" character varying NOT NULL, "weblink" character varying NOT NULL, "projectId" integer, "locationId" integer, CONSTRAINT "PK_c91eee45fe9516b4b5b616815b7" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "property_unit" ("id" SERIAL NOT NULL, "name" character varying(1024) NOT NULL, "symbol" character varying(32) NOT NULL, "multiplier" numeric(7,3) NOT NULL, "parentId" integer, CONSTRAINT "PK_709ee9f48a228162c82fcfaed31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "property_type" ("id" SERIAL NOT NULL, "name" character varying(1024) NOT NULL, "isNumeric" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_eb483bf7f6ddf612998949edd26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "property" ("uid" uuid NOT NULL DEFAULT uuid_generate_v4(), "value" character varying(64) NOT NULL, "elementUid" uuid, "propertyTypeId" integer, "propertyUnitId" integer, CONSTRAINT "PK_ee91f16e617e690e75d9fef665d" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "classification_system" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "description" character varying, "parentId" integer, CONSTRAINT "PK_d0581642dcdef373edf04da3158" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "classification_entry" ("id" SERIAL NOT NULL, "label" character varying(1024) NOT NULL, "code" character varying(128) NOT NULL, "classificationSystemId" integer, "parentId" integer, CONSTRAINT "PK_012a94e47e4c94d33c126858fd3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "file" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "originalName" character varying(255) NOT NULL, "uploadedBy" integer NOT NULL, "uploadedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP, "size" integer NOT NULL, "filePath" character varying NOT NULL, "fileType" character varying NOT NULL, CONSTRAINT "file-name-path" UNIQUE ("filePath", "name"), CONSTRAINT "PK_d85c96c207a7395158a68ee1265" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "inventory_file" ("uid" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "description" character varying(1024), "documentAuthor" character varying(255), "documentDate" TIMESTAMP, "projectId" integer, "fileUuid" uuid, "elementTypeUid" uuid, CONSTRAINT "unique-inventory-file" UNIQUE ("fileUuid"), CONSTRAINT "PK_de81c204795b3377070f08e7cdc" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "element_type" ("uid" uuid NOT NULL DEFAULT uuid_generate_v4(), "ifcId" character varying, "ifcType" character varying, "name" character varying NOT NULL, "description" character varying, "category" character varying, "historicalValue" character varying, "trademark" character varying, "designer" character varying, "projectId" integer, CONSTRAINT "unique_element_type_ifcid_project" UNIQUE ("ifcId", "projectId"), CONSTRAINT "unique_element_type_name_project" UNIQUE ("name", "projectId"), CONSTRAINT "PK_25306ff76986e6b5cdb350e32a4" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TYPE "public"."element_surfacedamage_enum" AS ENUM('none', 'low', 'medium', 'high')`);
        await queryRunner.query(`CREATE TYPE "public"."element_reusedecision_enum" AS ENUM('backfilling', 'recycling', 'reuse', 'undefined')`);
        await queryRunner.query(`CREATE TYPE "public"."element_hazardassessment_enum" AS ENUM('no_hazard', 'connection_only', 'surface_only', 'overall')`);
        await queryRunner.query(`CREATE TYPE "public"."element_hazardassessmentstatus_enum" AS ENUM('requested', 'in_progress', 'finished')`);
        await queryRunner.query(`CREATE TABLE "element" ("uid" uuid NOT NULL DEFAULT uuid_generate_v4(), "revitId" character varying, "ifcId" character varying, "name" character varying NOT NULL, "description" character varying, "reusePotential" numeric, "surfaceDamage" "public"."element_surfacedamage_enum", "reuseDecision" "public"."element_reusedecision_enum" DEFAULT 'undefined', "hazardAssessment" "public"."element_hazardassessment_enum" DEFAULT 'no_hazard', "hazardAssessmentStatus" "public"."element_hazardassessmentstatus_enum" DEFAULT 'requested', "projectId" integer, "elementTypeUid" uuid, "pointOfInterestUid" uuid, CONSTRAINT "unique_element_ifcid_project" UNIQUE ("ifcId", "projectId"), CONSTRAINT "PK_adb1c4c9b10d17a64345f230c4d" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "passport_file" ("uid" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "documentDate" TIMESTAMP, "projectId" integer, "fileUuid" uuid, "circularityUid" uuid, CONSTRAINT "unique-passport-file" UNIQUE ("fileUuid"), CONSTRAINT "PK_09c4872d08b762ae3d706edc71e" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "circularity" ("uid" uuid NOT NULL DEFAULT uuid_generate_v4(), "marketValue" numeric, "savingsCO2" numeric, "socialBalance" numeric, "projectId" integer, "elementTypeUid" uuid, "materialTypeUid" uuid, CONSTRAINT "REL_119878d79dd6a3104f59c73537" UNIQUE ("elementTypeUid"), CONSTRAINT "REL_14e10fb5e5e44a9134f1fa613c" UNIQUE ("materialTypeUid"), CONSTRAINT "PK_abb7b4711ef80d373e7ce331f5e" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "scan_config" ("id" SERIAL NOT NULL, "scanUrl" character varying(255) NOT NULL, "projectId" integer, CONSTRAINT "PK_c0fa9a0848de3d6747830c1cc49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_role" ("userId" integer NOT NULL, "roleId" integer NOT NULL, CONSTRAINT "PK_7b4e17a669299579dfa55a3fc35" PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`CREATE TABLE "role" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "longName" character varying(255) NOT NULL, "description" character varying(255) NOT NULL, CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "unique-role-name" ON "role" ("name") `);
        await queryRunner.query(`CREATE TABLE "bim_model" ("id" SERIAL NOT NULL, "clientId" character varying NOT NULL, "clientSecret" character varying NOT NULL, "scope" character varying, "urn" character varying NOT NULL, "formattedUrn" character varying NOT NULL, "zone" character varying DEFAULT 'US', "projectId" integer, CONSTRAINT "unique-project" UNIQUE ("projectId"), CONSTRAINT "PK_6e3cbc818529268f5007c04b640" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "forge_ifc_mapping" ("uid" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" integer NOT NULL, "forgeId" character varying NOT NULL, "ifcId" character varying NOT NULL, CONSTRAINT "PK_c69630af7f9f41c034280db5d02" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "project_file" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "description" character varying(1024), "documentAuthor" character varying(255), "documentDate" TIMESTAMP, "projectId" integer, "fileUuid" uuid, "locationId" integer, CONSTRAINT "unique-title-project" UNIQUE ("title", "projectId"), CONSTRAINT "PK_9e8bbc6ccf0af1d25fbfcddcc80" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "property_type_unit_rel" ("propertyTypeId" integer NOT NULL, "propertyUnitId" integer NOT NULL, CONSTRAINT "PK_dc2ec79d106fac0f269ce819ba6" PRIMARY KEY ("propertyTypeId", "propertyUnitId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7217eb9c42c509c42043a1417" ON "property_type_unit_rel" ("propertyTypeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8e1de11abeae1e71ad4aa9f617" ON "property_type_unit_rel" ("propertyUnitId") `);
        await queryRunner.query(`CREATE TABLE "element_type_classification_entry_rel" ("elementTypeUid" uuid NOT NULL, "classificationEntryId" integer NOT NULL, CONSTRAINT "PK_8da39af841f31121bc76dd756bf" PRIMARY KEY ("elementTypeUid", "classificationEntryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5b3811073bc8f9c92668fc23d5" ON "element_type_classification_entry_rel" ("elementTypeUid") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f3c0265fe663aaac37aa1cb77" ON "element_type_classification_entry_rel" ("classificationEntryId") `);
        await queryRunner.query(`CREATE TABLE "circularity_element_rel" ("circularityUid" uuid NOT NULL, "elementUid" uuid NOT NULL, CONSTRAINT "PK_19f4ab424b4f29e70b947887439" PRIMARY KEY ("circularityUid", "elementUid"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f93ec09a272bca2c2590b652af" ON "circularity_element_rel" ("circularityUid") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2ed8abdba6ef311c2f7b70320" ON "circularity_element_rel" ("elementUid") `);
        await queryRunner.query(`CREATE TABLE "project_location_closure" ("id_ancestor" integer NOT NULL, "id_descendant" integer NOT NULL, CONSTRAINT "PK_17a583ad2eee03ac32ee1badc78" PRIMARY KEY ("id_ancestor", "id_descendant"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2b3a121b92b8335ed4e12839f1" ON "project_location_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae47d3a81c0839a6e8ffc9313a" ON "project_location_closure" ("id_descendant") `);
        await queryRunner.query(`CREATE TABLE "property_unit_closure" ("id_ancestor" integer NOT NULL, "id_descendant" integer NOT NULL, CONSTRAINT "PK_9f9295fd49fc20389603e02b3a3" PRIMARY KEY ("id_ancestor", "id_descendant"))`);
        await queryRunner.query(`CREATE INDEX "IDX_89c7cf6b994fddd7742389efeb" ON "property_unit_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b7e98e15e2dd4e4b52c0079b3" ON "property_unit_closure" ("id_descendant") `);
        await queryRunner.query(`CREATE TABLE "classification_system_closure" ("id_ancestor" integer NOT NULL, "id_descendant" integer NOT NULL, CONSTRAINT "PK_f0362116ea1d6a54b9a6d92bb64" PRIMARY KEY ("id_ancestor", "id_descendant"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c7147e2b8c000f01f74b1c77f9" ON "classification_system_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9425670d26ff76839fa0fcc1e" ON "classification_system_closure" ("id_descendant") `);
        await queryRunner.query(`ALTER TABLE "project_address" ADD CONSTRAINT "FK_e0d07dea550d59fab79f008fc58" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_location" ADD CONSTRAINT "FK_bf2acf37726e5aae99a01f96125" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_location" ADD CONSTRAINT "FK_738e1d00ed78c153fe1a1a3bb0d" FOREIGN KEY ("parentLocationId") REFERENCES "project_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_participant" ADD CONSTRAINT "FK_bb5c66fd0c2c736e1506373f9fc" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_participant" ADD CONSTRAINT "FK_ccfc0ce731cbb9d6d97a5503a35" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_9884b2ee80eb70b7db4f12e8aed" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_type" ADD CONSTRAINT "FK_3889416134530892296459a42a1" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material" ADD CONSTRAINT "FK_9f4c4d96ddc4be39ba11b8483fe" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material" ADD CONSTRAINT "FK_00b2ebfa6c16992a038f7e3643f" FOREIGN KEY ("materialTypeUid") REFERENCES "material_type"("uid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material" ADD CONSTRAINT "FK_034f1f5cf3b38a4d63288bac0f7" FOREIGN KEY ("elementUid") REFERENCES "element"("uid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "point_of_interest" ADD CONSTRAINT "FK_c927d8d26ce7654f2673f072f84" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "point_of_interest" ADD CONSTRAINT "FK_f6c26c30d6db9d19b5bab824966" FOREIGN KEY ("locationId") REFERENCES "project_location"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_unit" ADD CONSTRAINT "FK_351b121877dc149d0ba2d92c6da" FOREIGN KEY ("parentId") REFERENCES "property_unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property" ADD CONSTRAINT "FK_847d35672e757ae42c11a7a5d39" FOREIGN KEY ("elementUid") REFERENCES "element"("uid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property" ADD CONSTRAINT "FK_7821015a476c9bfa0653b043cec" FOREIGN KEY ("propertyTypeId") REFERENCES "property_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property" ADD CONSTRAINT "FK_7e026f93c63c8eec8286d8010de" FOREIGN KEY ("propertyUnitId") REFERENCES "property_unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classification_system" ADD CONSTRAINT "FK_29a2105c2819a926832a18c0381" FOREIGN KEY ("parentId") REFERENCES "classification_system"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classification_entry" ADD CONSTRAINT "FK_800560e1c1642236cbc9d94a437" FOREIGN KEY ("classificationSystemId") REFERENCES "classification_system"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "classification_entry" ADD CONSTRAINT "FK_f8333d0bea0096838e583e9f675" FOREIGN KEY ("parentId") REFERENCES "classification_entry"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_file" ADD CONSTRAINT "FK_626b73c8935dca0f6f4d6196755" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_file" ADD CONSTRAINT "FK_3acebf0ff7b85f9474de9048984" FOREIGN KEY ("fileUuid") REFERENCES "file"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_file" ADD CONSTRAINT "FK_83e5791d30197d6f106c65ea704" FOREIGN KEY ("elementTypeUid") REFERENCES "element_type"("uid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "element_type" ADD CONSTRAINT "FK_1345444351b762ee91419766ee0" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "element" ADD CONSTRAINT "FK_e011ab8ac371e22e3eb5a55d9b4" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "element" ADD CONSTRAINT "FK_df3e182e00ab8d1cdf2f1218b6e" FOREIGN KEY ("elementTypeUid") REFERENCES "element_type"("uid") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "element" ADD CONSTRAINT "FK_071c8d8e71eebd5ce614c2b1b7d" FOREIGN KEY ("pointOfInterestUid") REFERENCES "point_of_interest"("uid") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport_file" ADD CONSTRAINT "FK_bcf54bed2fadf504bf7f581afeb" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport_file" ADD CONSTRAINT "FK_35baa25523e735062a17ea72cdd" FOREIGN KEY ("fileUuid") REFERENCES "file"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passport_file" ADD CONSTRAINT "FK_3ae54d419d98e9628368619e8ea" FOREIGN KEY ("circularityUid") REFERENCES "circularity"("uid") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circularity" ADD CONSTRAINT "FK_10578b67f894a37826ffdcbe9e2" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circularity" ADD CONSTRAINT "FK_119878d79dd6a3104f59c73537a" FOREIGN KEY ("elementTypeUid") REFERENCES "element_type"("uid") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circularity" ADD CONSTRAINT "FK_14e10fb5e5e44a9134f1fa613c6" FOREIGN KEY ("materialTypeUid") REFERENCES "material_type"("uid") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scan_config" ADD CONSTRAINT "FK_6c265f75590c2ce7f3c5eee4721" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bim_model" ADD CONSTRAINT "FK_f5f6dedfd8ff9230389c4f8754b" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_file" ADD CONSTRAINT "FK_f8b1098952dc5f55a00ee0c1f39" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_file" ADD CONSTRAINT "FK_0a8ccc39026387312acafda7b3b" FOREIGN KEY ("fileUuid") REFERENCES "file"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_file" ADD CONSTRAINT "FK_b1e8e99d520c03bb52447832aea" FOREIGN KEY ("locationId") REFERENCES "project_location"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_type_unit_rel" ADD CONSTRAINT "FK_a7217eb9c42c509c42043a1417e" FOREIGN KEY ("propertyTypeId") REFERENCES "property_type"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "property_type_unit_rel" ADD CONSTRAINT "FK_8e1de11abeae1e71ad4aa9f6171" FOREIGN KEY ("propertyUnitId") REFERENCES "property_unit"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "element_type_classification_entry_rel" ADD CONSTRAINT "FK_5b3811073bc8f9c92668fc23d53" FOREIGN KEY ("elementTypeUid") REFERENCES "element_type"("uid") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "element_type_classification_entry_rel" ADD CONSTRAINT "FK_4f3c0265fe663aaac37aa1cb775" FOREIGN KEY ("classificationEntryId") REFERENCES "classification_entry"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circularity_element_rel" ADD CONSTRAINT "FK_f93ec09a272bca2c2590b652afa" FOREIGN KEY ("circularityUid") REFERENCES "circularity"("uid") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "circularity_element_rel" ADD CONSTRAINT "FK_a2ed8abdba6ef311c2f7b70320b" FOREIGN KEY ("elementUid") REFERENCES "element"("uid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_location_closure" ADD CONSTRAINT "FK_2b3a121b92b8335ed4e12839f11" FOREIGN KEY ("id_ancestor") REFERENCES "project_location"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_location_closure" ADD CONSTRAINT "FK_ae47d3a81c0839a6e8ffc9313ae" FOREIGN KEY ("id_descendant") REFERENCES "project_location"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_unit_closure" ADD CONSTRAINT "FK_89c7cf6b994fddd7742389efebc" FOREIGN KEY ("id_ancestor") REFERENCES "property_unit"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_unit_closure" ADD CONSTRAINT "FK_6b7e98e15e2dd4e4b52c0079b3b" FOREIGN KEY ("id_descendant") REFERENCES "property_unit"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classification_system_closure" ADD CONSTRAINT "FK_c7147e2b8c000f01f74b1c77f9d" FOREIGN KEY ("id_ancestor") REFERENCES "classification_system"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classification_system_closure" ADD CONSTRAINT "FK_a9425670d26ff76839fa0fcc1eb" FOREIGN KEY ("id_descendant") REFERENCES "classification_system"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "classification_system_closure" DROP CONSTRAINT "FK_a9425670d26ff76839fa0fcc1eb"`);
        await queryRunner.query(`ALTER TABLE "classification_system_closure" DROP CONSTRAINT "FK_c7147e2b8c000f01f74b1c77f9d"`);
        await queryRunner.query(`ALTER TABLE "property_unit_closure" DROP CONSTRAINT "FK_6b7e98e15e2dd4e4b52c0079b3b"`);
        await queryRunner.query(`ALTER TABLE "property_unit_closure" DROP CONSTRAINT "FK_89c7cf6b994fddd7742389efebc"`);
        await queryRunner.query(`ALTER TABLE "project_location_closure" DROP CONSTRAINT "FK_ae47d3a81c0839a6e8ffc9313ae"`);
        await queryRunner.query(`ALTER TABLE "project_location_closure" DROP CONSTRAINT "FK_2b3a121b92b8335ed4e12839f11"`);
        await queryRunner.query(`ALTER TABLE "circularity_element_rel" DROP CONSTRAINT "FK_a2ed8abdba6ef311c2f7b70320b"`);
        await queryRunner.query(`ALTER TABLE "circularity_element_rel" DROP CONSTRAINT "FK_f93ec09a272bca2c2590b652afa"`);
        await queryRunner.query(`ALTER TABLE "element_type_classification_entry_rel" DROP CONSTRAINT "FK_4f3c0265fe663aaac37aa1cb775"`);
        await queryRunner.query(`ALTER TABLE "element_type_classification_entry_rel" DROP CONSTRAINT "FK_5b3811073bc8f9c92668fc23d53"`);
        await queryRunner.query(`ALTER TABLE "property_type_unit_rel" DROP CONSTRAINT "FK_8e1de11abeae1e71ad4aa9f6171"`);
        await queryRunner.query(`ALTER TABLE "property_type_unit_rel" DROP CONSTRAINT "FK_a7217eb9c42c509c42043a1417e"`);
        await queryRunner.query(`ALTER TABLE "project_file" DROP CONSTRAINT "FK_b1e8e99d520c03bb52447832aea"`);
        await queryRunner.query(`ALTER TABLE "project_file" DROP CONSTRAINT "FK_0a8ccc39026387312acafda7b3b"`);
        await queryRunner.query(`ALTER TABLE "project_file" DROP CONSTRAINT "FK_f8b1098952dc5f55a00ee0c1f39"`);
        await queryRunner.query(`ALTER TABLE "bim_model" DROP CONSTRAINT "FK_f5f6dedfd8ff9230389c4f8754b"`);
        await queryRunner.query(`ALTER TABLE "scan_config" DROP CONSTRAINT "FK_6c265f75590c2ce7f3c5eee4721"`);
        await queryRunner.query(`ALTER TABLE "circularity" DROP CONSTRAINT "FK_14e10fb5e5e44a9134f1fa613c6"`);
        await queryRunner.query(`ALTER TABLE "circularity" DROP CONSTRAINT "FK_119878d79dd6a3104f59c73537a"`);
        await queryRunner.query(`ALTER TABLE "circularity" DROP CONSTRAINT "FK_10578b67f894a37826ffdcbe9e2"`);
        await queryRunner.query(`ALTER TABLE "passport_file" DROP CONSTRAINT "FK_3ae54d419d98e9628368619e8ea"`);
        await queryRunner.query(`ALTER TABLE "passport_file" DROP CONSTRAINT "FK_35baa25523e735062a17ea72cdd"`);
        await queryRunner.query(`ALTER TABLE "passport_file" DROP CONSTRAINT "FK_bcf54bed2fadf504bf7f581afeb"`);
        await queryRunner.query(`ALTER TABLE "element" DROP CONSTRAINT "FK_071c8d8e71eebd5ce614c2b1b7d"`);
        await queryRunner.query(`ALTER TABLE "element" DROP CONSTRAINT "FK_df3e182e00ab8d1cdf2f1218b6e"`);
        await queryRunner.query(`ALTER TABLE "element" DROP CONSTRAINT "FK_e011ab8ac371e22e3eb5a55d9b4"`);
        await queryRunner.query(`ALTER TABLE "element_type" DROP CONSTRAINT "FK_1345444351b762ee91419766ee0"`);
        await queryRunner.query(`ALTER TABLE "inventory_file" DROP CONSTRAINT "FK_83e5791d30197d6f106c65ea704"`);
        await queryRunner.query(`ALTER TABLE "inventory_file" DROP CONSTRAINT "FK_3acebf0ff7b85f9474de9048984"`);
        await queryRunner.query(`ALTER TABLE "inventory_file" DROP CONSTRAINT "FK_626b73c8935dca0f6f4d6196755"`);
        await queryRunner.query(`ALTER TABLE "classification_entry" DROP CONSTRAINT "FK_f8333d0bea0096838e583e9f675"`);
        await queryRunner.query(`ALTER TABLE "classification_entry" DROP CONSTRAINT "FK_800560e1c1642236cbc9d94a437"`);
        await queryRunner.query(`ALTER TABLE "classification_system" DROP CONSTRAINT "FK_29a2105c2819a926832a18c0381"`);
        await queryRunner.query(`ALTER TABLE "property" DROP CONSTRAINT "FK_7e026f93c63c8eec8286d8010de"`);
        await queryRunner.query(`ALTER TABLE "property" DROP CONSTRAINT "FK_7821015a476c9bfa0653b043cec"`);
        await queryRunner.query(`ALTER TABLE "property" DROP CONSTRAINT "FK_847d35672e757ae42c11a7a5d39"`);
        await queryRunner.query(`ALTER TABLE "property_unit" DROP CONSTRAINT "FK_351b121877dc149d0ba2d92c6da"`);
        await queryRunner.query(`ALTER TABLE "point_of_interest" DROP CONSTRAINT "FK_f6c26c30d6db9d19b5bab824966"`);
        await queryRunner.query(`ALTER TABLE "point_of_interest" DROP CONSTRAINT "FK_c927d8d26ce7654f2673f072f84"`);
        await queryRunner.query(`ALTER TABLE "material" DROP CONSTRAINT "FK_034f1f5cf3b38a4d63288bac0f7"`);
        await queryRunner.query(`ALTER TABLE "material" DROP CONSTRAINT "FK_00b2ebfa6c16992a038f7e3643f"`);
        await queryRunner.query(`ALTER TABLE "material" DROP CONSTRAINT "FK_9f4c4d96ddc4be39ba11b8483fe"`);
        await queryRunner.query(`ALTER TABLE "material_type" DROP CONSTRAINT "FK_3889416134530892296459a42a1"`);
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_9884b2ee80eb70b7db4f12e8aed"`);
        await queryRunner.query(`ALTER TABLE "project_participant" DROP CONSTRAINT "FK_ccfc0ce731cbb9d6d97a5503a35"`);
        await queryRunner.query(`ALTER TABLE "project_participant" DROP CONSTRAINT "FK_bb5c66fd0c2c736e1506373f9fc"`);
        await queryRunner.query(`ALTER TABLE "project_location" DROP CONSTRAINT "FK_738e1d00ed78c153fe1a1a3bb0d"`);
        await queryRunner.query(`ALTER TABLE "project_location" DROP CONSTRAINT "FK_bf2acf37726e5aae99a01f96125"`);
        await queryRunner.query(`ALTER TABLE "project_address" DROP CONSTRAINT "FK_e0d07dea550d59fab79f008fc58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9425670d26ff76839fa0fcc1e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c7147e2b8c000f01f74b1c77f9"`);
        await queryRunner.query(`DROP TABLE "classification_system_closure"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b7e98e15e2dd4e4b52c0079b3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89c7cf6b994fddd7742389efeb"`);
        await queryRunner.query(`DROP TABLE "property_unit_closure"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae47d3a81c0839a6e8ffc9313a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b3a121b92b8335ed4e12839f1"`);
        await queryRunner.query(`DROP TABLE "project_location_closure"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2ed8abdba6ef311c2f7b70320"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f93ec09a272bca2c2590b652af"`);
        await queryRunner.query(`DROP TABLE "circularity_element_rel"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f3c0265fe663aaac37aa1cb77"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b3811073bc8f9c92668fc23d5"`);
        await queryRunner.query(`DROP TABLE "element_type_classification_entry_rel"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e1de11abeae1e71ad4aa9f617"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7217eb9c42c509c42043a1417"`);
        await queryRunner.query(`DROP TABLE "property_type_unit_rel"`);
        await queryRunner.query(`DROP TABLE "project_file"`);
        await queryRunner.query(`DROP TABLE "forge_ifc_mapping"`);
        await queryRunner.query(`DROP TABLE "bim_model"`);
        await queryRunner.query(`DROP INDEX "public"."unique-role-name"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TABLE "user_role"`);
        await queryRunner.query(`DROP TABLE "scan_config"`);
        await queryRunner.query(`DROP TABLE "circularity"`);
        await queryRunner.query(`DROP TABLE "passport_file"`);
        await queryRunner.query(`DROP TABLE "element"`);
        await queryRunner.query(`DROP TYPE "public"."element_hazardassessmentstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."element_hazardassessment_enum"`);
        await queryRunner.query(`DROP TYPE "public"."element_reusedecision_enum"`);
        await queryRunner.query(`DROP TYPE "public"."element_surfacedamage_enum"`);
        await queryRunner.query(`DROP TABLE "element_type"`);
        await queryRunner.query(`DROP TABLE "inventory_file"`);
        await queryRunner.query(`DROP TABLE "file"`);
        await queryRunner.query(`DROP TABLE "classification_entry"`);
        await queryRunner.query(`DROP TABLE "classification_system"`);
        await queryRunner.query(`DROP TABLE "property"`);
        await queryRunner.query(`DROP TABLE "property_type"`);
        await queryRunner.query(`DROP TABLE "property_unit"`);
        await queryRunner.query(`DROP TABLE "point_of_interest"`);
        await queryRunner.query(`DROP TABLE "material"`);
        await queryRunner.query(`DROP TABLE "material_type"`);
        await queryRunner.query(`DROP INDEX "public"."unique-project-shortName"`);
        await queryRunner.query(`DROP TABLE "project"`);
        await queryRunner.query(`DROP TYPE "public"."project_projecttype_enum"`);
        await queryRunner.query(`DROP TABLE "project_participant"`);
        await queryRunner.query(`DROP TYPE "public"."project_participant_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."unique-user-salt"`);
        await queryRunner.query(`DROP INDEX "public"."unique-user-login"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "project_location"`);
        await queryRunner.query(`DROP TYPE "public"."project_location_type_enum"`);
        await queryRunner.query(`DROP TABLE "project_address"`);
    }

}
